CREATE DATABASE IF NOT EXISTS hbnb_test_db;
CREATE USER IF NOT EXISTS 'hbnb_test'@'localhost' IDENTIFIED BY 'hbnb_test_pwd';
GRANT ALL PRIVILEGES ON hbnb_test_db.* TO 'hbnb_test'@'localhost';
GRANT SELECT ON performance_schema.* TO 'hbnb_test'@'localhost';
FLUSH PRIVILEGES;

USE hbnb_test_db;

CREATE TABLE IF NOT EXISTS states (
   id VARCHAR(60) NOT NULL PRIMARY KEY,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   name VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS cities (
   id VARCHAR(60) NOT NULL PRIMARY KEY,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   name VARCHAR(128) NOT NULL,
   state_id VARCHAR(60) NOT NULL,
   FOREIGN KEY (state_id) REFERENCES states(id)
);

CREATE TABLE IF NOT EXISTS users (
   id VARCHAR(60) NOT NULL PRIMARY KEY,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   email VARCHAR(128) NOT NULL,
   password VARCHAR(128) NOT NULL,
   first_name VARCHAR(128),
   last_name VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS places (
   id VARCHAR(60) NOT NULL PRIMARY KEY,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   city_id VARCHAR(60) NOT NULL,
   user_id VARCHAR(60) NOT NULL,
   name VARCHAR(128) NOT NULL,
   description VARCHAR(1024),
   number_rooms INT NOT NULL DEFAULT 0,
   number_bathrooms INT NOT NULL DEFAULT 0,
   max_guest INT NOT NULL DEFAULT 0,
   price_by_night INT NOT NULL DEFAULT 0,
   latitude FLOAT,
   longitude FLOAT,
   FOREIGN KEY (city_id) REFERENCES cities(id),
   FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reviews (
   id VARCHAR(60) NOT NULL PRIMARY KEY,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   place_id VARCHAR(60) NOT NULL,
   user_id VARCHAR(60) NOT NULL,
   text VARCHAR(1024) NOT NULL,
   FOREIGN KEY (place_id) REFERENCES places(id),
   FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS amenities (
   id VARCHAR(60) NOT NULL PRIMARY KEY,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   name VARCHAR(128) NOT NULL
);
